In [25]:
# how to create csv, excel, dictionary,tuples and list of dictionary

import pandas as pd
import numpy as np
df = pd.read_csv(r"D:\Downloads\_Sales.csv")
print(df)
print(df.loc[:,['SalesId','Quantity']])
res = df.loc[df['Quantity']>70,['SalesId','Quantity']]

print(pd.DataFrame(np.sort(res),columns=['A','B']))
print(res_1.loc[0,'A'] == 93)

        SalesId  StoreId  ProductId        Date  UnitPrice  Quantity
0         82319    22726        590  02/12/2019     0.0525        93
1         15022    21754        390  19/11/2017     5.1100        28
2         11624    71053        883  13/07/2020     7.3675        33
3         63101    22914        658  12/05/2019     2.0825        76
4         29702    22623        632  20/07/2020     0.6475         8
...         ...      ...        ...         ...        ...       ...
199995    57660    85123        682  01/07/2019     4.4625        75
199996    18783    22727        656  18/04/2017     1.6800        30
199997    25064    22912        831  10/06/2019     2.5025        60
199998    43683    22622        902  06/08/2018     3.2025        98
199999    44211    22749        775  22/06/2018     1.8550        32

[200000 rows x 6 columns]
        SalesId  Quantity
0         82319        93
1         15022        28
2         11624        33
3         63101        76
4         29702         8
...         ...       ...
199995    57660        75
199996    18783        30
199997    25064        60
199998    43683        98
199999    44211        32

[200000 rows x 2 columns]
        A      B
0      93  82319
1      76  63101
2      93  35660
3      98  69913
4      78  60346
...    ..    ...
59707  75  44628
59708  96  50281
59709  81  46931
59710  75  57660
59711  98  43683

[59712 rows x 2 columns]
True

In [ ]:
df.apply()

In [32]:
df.loc[df['Quantity']>70,'sales_label'] = 'High'
df.loc[df['Quantity']<=70,'sales_label'] = 'Low'
print(df)

        SalesId  StoreId  ProductId        Date  UnitPrice  Quantity  \
0         82319    22726        590  02/12/2019     0.0525        93
1         15022    21754        390  19/11/2017     5.1100        28
2         11624    71053        883  13/07/2020     7.3675        33
3         63101    22914        658  12/05/2019     2.0825        76
4         29702    22623        632  20/07/2020     0.6475         8
...         ...      ...        ...         ...        ...       ...
199995    57660    85123        682  01/07/2019     4.4625        75
199996    18783    22727        656  18/04/2017     1.6800        30
199997    25064    22912        831  10/06/2019     2.5025        60
199998    43683    22622        902  06/08/2018     3.2025        98
199999    44211    22749        775  22/06/2018     1.8550        32

       sales-label sales_label
0             High        High
1              Low         Low
2              Low         Low
3             High        High
4              Low         Low
...            ...         ...
199995        High        High
199996         Low         Low
199997         Low         Low
199998        High        High
199999         Low         Low

[200000 rows x 8 columns]

In [54]:

df.loc[:,'Quantity'].sort_values(ascending=False)

40437     100
78010     100
40418     100
164522    100
82698     100
         ...
143109      1
199887      1
72566       1
189814      1
27380       1
Name: Quantity, Length: 200000, dtype: int64

In [ ]:
df = pd.read_excel(r"D:\Downloads\Sales.xlsx", sheet_name='Products') # when put (sheet_name= None), it shows all sheet
df

In [3]:
print(df.keys())

dict_keys(['Sales', 'Products', 'Inventory'])

In [4]:
cricket_match = {
    'HCC': ['Kerava','Tusula'],
    'Tampere': ['tampere_cup','TCC']
}
df = pd.DataFrame(cricket_match)
df

      HCC      Tampere
0  Kerava  tampere_cup
1  Tusula          TCC

In [5]:
cricket_match_tuple = (
    ['Kerava','Tusula'],
    ['tampere_cup','TCC']
)
df = pd.DataFrame(cricket_match_tuple,columns=['HCC','TCC'])
df

           HCC     TCC
0       Kerava  Tusula
1  tampere_cup     TCC

In [6]:
#list of dic
cricket_match = [
    {'HCC': ('Kerava','Tusula'),
    'tampere_cup': ('tampere_cup','TCC')}
]
df = pd.DataFrame(data= cricket_match,columns=['HCC','tampere_cup'])
df

                HCC         tampere_cup
0  (Kerava, Tusula)  (tampere_cup, TCC)

In [7]:
df = pd.read_clipboard()
print(df)

    SalesId  StoreId  ProductId        Date UnitPrice  Quantity
0     82319    22726        590  2019-12-02    0,0525        93
1     15022    21754        390  2017-11-19      5,11        28
2     11624    71053        883  2020-07-13    7,3675        33
3     63101    22914        658  2019-05-12    2,0825        76
4     29702    22623        632  2020-07-20    0,6475         8
5     35660    22749        170  2019-09-30      5,67        93
6     69913    22633        444  2017-11-03    0,4375        98
7     47278    84969        184  2018-04-17     9,205        17
8     46126    48187        316  2017-10-13     3,395        47
9     69718    22726        972  2018-09-12    1,5925        43
10    69297    21755        533  2017-01-27    3,7625        24
11    22911    22633         65  2017-01-15      1,82        54
12    52225    22913        667  2019-09-18      8,82        35
13    84229    21755        580  2019-12-13      1,33         2
14    60346    37444        267  2018-01-13      2,94        78
15    87185    22748        692  2019-12-31    4,6725         6
16    82434    22748        922  2020-04-29    0,7875        68
17    21699    85123        198  2018-08-25    2,6075        53
18    51987    22632        158  2019-03-06    2,8175        53
19    18823    21777        589  2019-01-05     0,245        98
20    72877    22745        916  2019-10-11      4,97        49
21    67141    10002         44  2019-09-05      2,38        18
22    59436    22745        441  2020-04-17      1,68        82

In [16]:
import pandas as pd
import numpy as np

a = np.arange(10,1000,50)
print(a)
df = pd.DataFrame(a,columns=['serial'])
print(df)

[ 10  60 110 160 210 260 310 360 410 460 510 560 610 660 710 760 810 860
 910 960]
    serial
0       10
1       60
2      110
3      160
4      210
5      260
6      310
7      360
8      410
9      460
10     510
11     560
12     610
13     660
14     710
15     760
16     810
17     860
18     910
19     960

In [28]:

df = pd.DataFrame(np.array([[10,20,30,40,50],[60,70,80,90,100],[110,120,130,140,150]]),columns=['small','Medium','Large','o','p'])
print(df)

   small  Medium  Large    o    p
0     10      20     30   40   50
1     60      70     80   90  100
2    110     120    130  140  150

In [26]:
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                  columns=['a', 'b', 'c'])
df2

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [65]:
#loc works with label and iloc only works with integer
import pandas as pd
data = pd.DataFrame({
    'Name': ['Ahasan','Hasan','Arham','Nahuan','Akib'],
    'Age': [35,34,1,5,7],
    'City': ['Helsinki','stockhome','Kuopio','Lahti','Sydney']
})
print(data)
print(data.loc[3])
print(data.iloc[3])

     Name  Age       City
0  Ahasan   35   Helsinki
1   Hasan   34  stockhome
2   Arham    1     Kuopio
3  Nahuan    5      Lahti
4    Akib    7     Sydney
Name    Nahuan
Age          5
City     Lahti
Name: 3, dtype: object
Name    Nahuan
Age          5
City     Lahti
Name: 3, dtype: object

In [66]:
data.index =['A','B','C','D','E']
print(data)
print(data.loc['C'])
data.iloc[0]

     Name  Age       City
A  Ahasan   35   Helsinki
B   Hasan   34  stockhome
C   Arham    1     Kuopio
D  Nahuan    5      Lahti
E    Akib    7     Sydney
Name     Arham
Age          1
City    Kuopio
Name: C, dtype: object

Name      Ahasan
Age           35
City    Helsinki
Name: A, dtype: object

In [80]:
data.loc['C','Name']
data.iloc [0,2]
print(data.loc[:,['Name','Age']])
print(data.loc[['A','C']])
print(data.iloc[[0,3]])

     Name  Age
A  Ahasan   35
B   Hasan   34
C   Arham    1
D  Nahuan    5
E    Akib    7
     Name  Age      City
A  Ahasan   35  Helsinki
C   Arham    1    Kuopio
     Name  Age      City
A  Ahasan   35  Helsinki
D  Nahuan    5     Lahti

In [86]:
#slicing loc and iloc
print(data)
print(data.loc[['A','C']])
print(data.iloc[2:3,3:4])

     Name  Age       City
A  Ahasan   35   Helsinki
B   Hasan   34  stockhome
C   Arham    1     Kuopio
D  Nahuan    5      Lahti
E    Akib    7     Sydney
     Name  Age      City
A  Ahasan   35  Helsinki
C   Arham    1    Kuopio
Empty DataFrame
Columns: []
Index: [C]

In [100]:
# conditional filtering by loc, here () is very important to remember

print(data.loc[data['Age']<15])  # one condition

print(data.loc[(data['Age']>5) & (data['City']=='Helsinki')]) # two conditions with AND

print(data.loc[(data['City'] == 'Helsinki') | (data['Age']<7)]) # TWO conditions with OR

print(data.loc[data['Age']<10,['Name','City']])  # CONDITION WITH SELECTED COLUMN  '''df.loc[condition, columns]'''এই pattern-টা খুব ভালোভাবে মনে রাখুন।

     Name  Age    City
C   Arham    1  Kuopio
D  Nahuan    5   Lahti
E    Akib    7  Sydney
     Name  Age      City
A  Ahasan   35  Helsinki
     Name  Age      City
A  Ahasan   35  Helsinki
C   Arham    1    Kuopio
D  Nahuan    5     Lahti
     Name    City
C   Arham  Kuopio
D  Nahuan   Lahti
E    Akib  Sydney